title: Community Starter Kit
tagline: Transform your code into a welcoming open source project
description: There are millions of projects on GitHub, all competing for attention from the millions of open source contributors available to help. Learn how to help your project stand out.
tags:
  - GitHub
  - Open Source
template:
  name: community-starter-kit
  url: https://github.com/githubtraining/community-starter-kit-template.git
before:
  - type: createIssue
    title: Preparing Mona's project for open source
    body: 01-welcome-story.md
    comments:
      - 01a-add-description.md
steps:
  - title: Add a repository description
    description: Welcome users to the repository with a descriptive README
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/issues/1
    event: issues.closed
    actions:
      - type: createPullRequest
        title: Add a repository description
        body: 02-create-readme.md
        head: add-readme
        action_id: pr
      - type: respond
        with: 01n-next.md
        data:
          prURL: '%actions.pr.data.html_url%'

  - title: Edit the README
    description: Describe the purpose and benefits of your project
    event: pull_request.synchronize
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pulls
    actions:
      - type: getFileContents
        filename: README.md
        action_id: readme
      - type: gate
        left: '/DESCRIPTION PLACEHOLDER/'
        operator: '!test'
        right: '%actions.readme%'
        else:
          type: respond
          with: 02a-readme-description.md
      - type: gate
        left: '/FEATURES PLACEHOLDER/'
        operator: '!test'
        right: '%actions.readme%'
        else:
          type: respond
          with: 02b-readme-features.md
      - type: respond
        with: 02c-readme-done.md

  - title: Merge the README
    description: Merge the pull request to add the README
    event: pull_request.closed
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pulls
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: createPullRequest
        head: add-docs
        title: Add documentation
        body: 03-add-docs.md
        action_id: pr
      - type: respond
        with: 02n-next.md
        data:
          prURL: '%actions.pr.data.html_url%'

  - title: Create user documentation
    description: Support your users with great documentation
    event: pull_request.synchronize
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pulls
    actions:
      - type: getFileContents
        filename: docs/getting-started.md
        action_id: file
      - type: gate
        left: '/CONFIGS PLACEHOLDER/'
        operator: '!test'
        right: '%actions.file%'
        else:
          type: respond
          with: 03a-docs-configs.md
      - type: respond
        with: 03b-docs-done.md

  - title: Merge the user documentation
    description: Merge the pull request to add the user documentation
    event: pull_request.closed
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pulls
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: createPullRequest
        head: add-issue-template
        title: Add an issue template
        body: 04-helping-contributors.md
        action_id: pr
      - type: respond
        with: 03n-next.md
        data:
          prURL: '%actions.pr.data.html_url%'

  - title: Add an issue template
    description: Use issue templates to gather useful information from contributors
    event: pull_request.synchronize
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pulls
    actions:
      - type: getTree
        action_id: tree
        recursive: true
        sha: '%payload.pull_request.head.sha%'
      - type: gate
        left: '%actions.tree.data.tree%'
        operator: includes
        right: path:/^.github/ISSUE_TEMPLATE/bug-report.md$/
        else:
          type: respond
          with: 04a-template-location.md
      - type: respond
        with: 04b-template-done.md

  - title: Merge the issue template
    description: Merge the pull request to add your issue template
    event: pull_request.closed
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pulls
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: createPullRequest
        head: add-contrib-guide
        title: Add a contributing guide
        body: 05-contributing-guide.md
        action_id: pr
      - type: respond
        with: 04n-next.md
        data:
          prURL: '%actions.pr.data.html_url%'

  - title: Add a CONTRIBUTING guide
    description: A CONTRIBUTING guide is used to tell others how they can help
    event: pull_request.synchronize
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pulls
    actions:
      - type: getFileContents
        filename: CONTRIBUTING.md
        action_id: file
      - type: gate
        left: '/DESCRIPTION PLACEHOLDER/'
        operator: '!test'
        right: '%actions.file%'
        else:
          type: respond
          with: 05a-contributing-labels.md
      - type: respond
        with: 06-add-labels.md

  - title: Add custom labels to your project
    description: Create the labels described in the CONTRIBUTING guide and add them to this pull request
    event: pull_request.labeled
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pulls
    actions:
      - type: respond
        with: 06a-label-done.md

  - title: Merge the CONTRIBUTING guide
    description: Merge the pull request to add your contributing guide
    event: pull_request.closed
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pulls
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: createPullRequest
        head: add-license
        title: Add a license
        body: 07-add-license.md
        action_id: pr
      - type: respond
        with: 06n-next.md
        data:
          prURL: '%actions.pr.data.html_url%'

  - title: Add the license
    description: Add a license to your open source project
    event: pull_request.synchronize
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pulls
    actions:
      - type: getFileContents
        filename: LICENSE.md
        action_id: file
      - type: gate
        left: '/\[year\]|\[fullname\]/'
        operator: '!test'
        right: '%actions.file%'
        else:
          type: respond
          with: 07a-replace-placeholders.md
      - type: respond
        with: 07b-license-done.md

  - title: Merge the license
    description: Merge the pull request to add your license
    event: pull_request.closed
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pulls
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: createPullRequest
        head: add-code
        title: Add a Code of Conduct
        body: 08-code-of-conduct.md
        action_id: pr
      - type: respond
        with: 07n-next.md
        data:
          prURL: '%actions.pr.data.html_url%'

  - title: Add the Code of Conduct
    description: Add a Code of Conduct to set expectations for behavior in your project
    event: pull_request.synchronize
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pulls
    actions:
      - type: getFileContents
        filename: code-of-conduct.md
        action_id: file
      - type: gate
        left: '/CONTRIBUTOR CODE/'
        operator: '!test'
        right: '%actions.file%'
        else:
          type: respond
          with: 08a-replace-placeholders.md
      - type: respond
        with: 08b-code-done.md

  - title: Merge the Code of Conduct
    description: Merge the pull request to add your Code of Conduct
    event: pull_request.closed
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/pulls
    actions:
      - type: gate
        left: '%payload.pull_request.merged%'
      - type: createIssue
        title: Make it visible
        body: 09-make-it-visible.md
        action_id: issue
      - type: respond
        with: 08n-next.md
        data:
          issueURL: '%actions.issue.data.html_url%'

  - title: Help users find the project
    description: Add repository topics to help GitHub categorize and recommend your project
    event: issues.closed
    link: https://github.com/{{ user.username }}/{{ course.template.name }}/issues
    actions:
      - type: respond
        with: 10-finish.md
